//! v0.3c compose import: reverse-engineer a `compose.yaml` from running
//! containers.
//!
//! The agent inspects each container in a stack via bollard and walks the
//! field map below to emit a YAML document the user can read, version,
//! and (in v0.3d) hand-edit.
//!
//! | Inspect field                         | Compose key                              |
//! |---------------------------------------|------------------------------------------|
//! | `Config.Image`                        | `image`                                  |
//! | `Config.Cmd`                          | `command`                                |
//! | `Config.Entrypoint`                   | `entrypoint`                             |
//! | `HostConfig.PortBindings`             | `ports`                                  |
//! | `HostConfig.Binds` + `Mounts`         | `volumes`                                |
//! | `Config.Env`                          | `environment` (compose-injected stripped)|
//! | `Config.Healthcheck`                  | `healthcheck`                            |
//! | `HostConfig.RestartPolicy`            | `restart`                                |
//! | `Config.Labels`                       | `labels` (compose-injected stripped)     |
//! | `NetworkSettings.Networks`            | `networks` (skip bridge/host/none)       |
//!
//! Lossy by design: build context, env interpolation, comments, anchors,
//! and `depends_on` are gone after `docker run`. The header comment in the
//! emitted YAML calls this out, and the dashboard banner re-iterates it.

use std::collections::{BTreeMap, BTreeSet};

use bollard::secret::{ContainerInspectResponse, MountTypeEnum, RestartPolicyNameEnum};
use serde_yaml::{Mapping, Value};

/// The header that's prepended to every generated compose.yaml. Pinned in
/// the snapshot test so changes are intentional.
pub const HEADER: &str = "# Generated by Isengard v0.3c compose-import\n# Do not edit if you want regeneration to overwrite you.\n# Move to Isengard-managed mode with: isd adopt <stack>  (v0.3d)\n";

/// Build a compose.yaml document for `stack_name` from the inspected
/// containers belonging to it. Containers must already be filtered to one
/// stack (the caller groups by `com.docker.compose.project` /
/// `isengard.stack`); this function trusts the slice.
///
/// `host_id`, when set, drives the `x-isengard.host` extension so the
/// multi-host bootstrap stays unambiguous. `None` skips the extension
/// (single-host stacks).
pub fn build_compose(
    stack_name: &str,
    containers: &[ContainerInspectResponse],
    host_id: Option<&str>,
) -> anyhow::Result<String> {
    let mut root = Mapping::new();

    // Top-level `x-isengard.host` extension for multi-host stacks. Compose
    // ignores `x-` keys but our v0.3d sync path will read them back.
    if let Some(hid) = host_id {
        root.insert(
            Value::String("x-isengard.host".to_string()),
            Value::String(hid.to_string()),
        );
    }

    // version: omitted on purpose. Compose v2+ treats top-level `version`
    // as deprecated and warns on every run.

    // services: alphabetical for stable diffs.
    let mut services_map: BTreeMap<String, Value> = BTreeMap::new();
    let mut all_networks: BTreeSet<String> = BTreeSet::new();

    for inspect in containers {
        let svc_name = service_name(inspect)?;
        let (svc_value, networks) = build_service(inspect)?;
        services_map.insert(svc_name, svc_value);
        for n in networks {
            all_networks.insert(n);
        }
    }

    let mut services = Mapping::new();
    for (name, value) in services_map {
        services.insert(Value::String(name), value);
    }
    root.insert(Value::String("services".into()), Value::Mapping(services));

    if !all_networks.is_empty() {
        let mut networks = Mapping::new();
        for net in all_networks {
            // Mark as external. We're documenting the runtime view, not a
            // network compose should create. The user can flip this when
            // they pull the file under their own `docker compose up`.
            let mut body = Mapping::new();
            body.insert(Value::String("external".into()), Value::Bool(true));
            networks.insert(Value::String(net), Value::Mapping(body));
        }
        root.insert(Value::String("networks".into()), Value::Mapping(networks));
    }

    let body = serde_yaml::to_string(&Value::Mapping(root))
        .map_err(|e| anyhow::anyhow!("emit compose.yaml: {e}"))?;

    let _ = stack_name; // reserved for future extension fields
    Ok(format!("{HEADER}{body}"))
}

/// Pick a service name from a container's inspect response. Prefers the
/// `com.docker.compose.service` label (the canonical service name), then
/// falls back to the container name with the leading `/` stripped.
fn service_name(inspect: &ContainerInspectResponse) -> anyhow::Result<String> {
    if let Some(name) = inspect
        .config
        .as_ref()
        .and_then(|c| c.labels.as_ref())
        .and_then(|l| l.get("com.docker.compose.service"))
    {
        return Ok(name.clone());
    }
    if let Some(name) = inspect.name.as_deref() {
        return Ok(name.trim_start_matches('/').to_string());
    }
    Err(anyhow::anyhow!(
        "container has neither name nor compose.service label"
    ))
}

/// Build one entry under `services:`. Returns the YAML value plus the set
/// of network names referenced (so the top-level `networks:` block can be
/// emitted with the right keys).
fn build_service(inspect: &ContainerInspectResponse) -> anyhow::Result<(Value, BTreeSet<String>)> {
    let mut svc = Mapping::new();
    let mut nets: BTreeSet<String> = BTreeSet::new();

    // image
    if let Some(image) = inspect.config.as_ref().and_then(|c| c.image.as_ref()) {
        svc.insert(Value::String("image".into()), Value::String(image.clone()));
    }

    // container_name: emitted only when it differs from the default
    // `<project>_<service>_1` style. We can't compute the default without
    // reading `com.docker.compose.project`; just pass the actual name
    // through. Compose with `container_name` ignores the auto-rename.
    if let Some(name) = inspect.name.as_deref() {
        let trimmed = name.trim_start_matches('/').to_string();
        svc.insert(
            Value::String("container_name".into()),
            Value::String(trimmed),
        );
    }

    // entrypoint / command
    if let Some(cfg) = inspect.config.as_ref() {
        if let Some(ep) = cfg.entrypoint.as_ref() {
            if !ep.is_empty() {
                svc.insert(Value::String("entrypoint".into()), string_seq(ep));
            }
        }
        if let Some(cmd) = cfg.cmd.as_ref() {
            if !cmd.is_empty() {
                svc.insert(Value::String("command".into()), string_seq(cmd));
            }
        }
    }

    // ports (HostConfig.PortBindings)
    if let Some(host_cfg) = inspect.host_config.as_ref() {
        if let Some(pb) = host_cfg.port_bindings.as_ref() {
            let ports = build_ports(pb);
            if !ports.is_empty() {
                svc.insert(
                    Value::String("ports".into()),
                    Value::Sequence(ports.into_iter().map(Value::String).collect()),
                );
            }
        }
    }

    // volumes (Binds + Mounts)
    let volumes = build_volumes(inspect);
    if !volumes.is_empty() {
        svc.insert(
            Value::String("volumes".into()),
            Value::Sequence(volumes.into_iter().map(Value::String).collect()),
        );
    }

    // environment (filter compose-injected vars)
    if let Some(env) = inspect.config.as_ref().and_then(|c| c.env.as_ref()) {
        let env_map = build_environment(env);
        if !env_map.is_empty() {
            let mut m = Mapping::new();
            for (k, v) in env_map {
                m.insert(Value::String(k), Value::String(v));
            }
            svc.insert(Value::String("environment".into()), Value::Mapping(m));
        }
    }

    // healthcheck
    if let Some(hc) = inspect.config.as_ref().and_then(|c| c.healthcheck.as_ref()) {
        if let Some(h) = build_healthcheck(hc) {
            svc.insert(Value::String("healthcheck".into()), Value::Mapping(h));
        }
    }

    // restart
    if let Some(restart) = inspect
        .host_config
        .as_ref()
        .and_then(|h| h.restart_policy.as_ref())
        .and_then(|r| r.name)
    {
        if let Some(s) = restart_policy_str(restart) {
            svc.insert(Value::String("restart".into()), Value::String(s.into()));
        }
    }

    // labels (drop compose.* / managed-by)
    if let Some(labels) = inspect.config.as_ref().and_then(|c| c.labels.as_ref()) {
        let kept = filter_labels(labels);
        if !kept.is_empty() {
            let mut m = Mapping::new();
            for (k, v) in kept {
                m.insert(Value::String(k), Value::String(v));
            }
            svc.insert(Value::String("labels".into()), Value::Mapping(m));
        }
    }

    // networks (skip bridge/host/none)
    if let Some(net_settings) = inspect.network_settings.as_ref() {
        if let Some(networks_map) = net_settings.networks.as_ref() {
            let mut svc_nets: Vec<String> = Vec::new();
            for name in networks_map.keys() {
                if matches!(name.as_str(), "bridge" | "host" | "none") {
                    continue;
                }
                svc_nets.push(name.clone());
                nets.insert(name.clone());
            }
            svc_nets.sort();
            if !svc_nets.is_empty() {
                svc.insert(
                    Value::String("networks".into()),
                    Value::Sequence(svc_nets.into_iter().map(Value::String).collect()),
                );
            }
        }
    }

    Ok((Value::Mapping(svc), nets))
}

/// Convert a `HostConfig.PortBindings` map (`"80/tcp" -> [{HostIp, HostPort}]`)
/// into compose-style `"127.0.0.1:8080:80/tcp"` entries. Sorted for stable
/// diffs.
fn build_ports(
    bindings: &std::collections::HashMap<String, Option<Vec<bollard::secret::PortBinding>>>,
) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    let mut keys: Vec<&String> = bindings.keys().collect();
    keys.sort();
    for cport in keys {
        let Some(Some(bindings)) = bindings.get(cport).map(|v| v.as_ref()) else {
            continue;
        };
        for b in bindings {
            let host_ip = b.host_ip.as_deref().unwrap_or("");
            let host_port = b.host_port.as_deref().unwrap_or("");
            // cport is "80/tcp" or "53/udp". Drop "/tcp" since compose
            // defaults to TCP; keep "/udp", "/sctp" verbatim.
            let cport_compose: String = match cport.split_once('/') {
                Some((p, "tcp")) => p.to_string(),
                _ => cport.clone(),
            };
            let s = match (host_ip, host_port) {
                ("", "") => cport_compose, // PublishAllPorts auto-allocated; rare
                ("", port) => format!("{port}:{cport_compose}"),
                (ip, port) => format!("{ip}:{port}:{cport_compose}"),
            };
            out.push(s);
        }
    }
    out.sort();
    out
}

/// Merge `HostConfig.Binds` (legacy `host:container[:ro]`) with
/// `HostConfig.Mounts` (typed bind/volume specs). De-dupes: a `volume`
/// type Mount usually has a Bind echo for the same target, and we keep
/// the first one. Sorted for stable diffs.
fn build_volumes(inspect: &ContainerInspectResponse) -> Vec<String> {
    let mut seen: BTreeSet<String> = BTreeSet::new();
    let mut out: Vec<String> = Vec::new();

    if let Some(binds) = inspect.host_config.as_ref().and_then(|h| h.binds.as_ref()) {
        for b in binds {
            if seen.insert(b.clone()) {
                out.push(b.clone());
            }
        }
    }

    if let Some(mounts) = inspect.host_config.as_ref().and_then(|h| h.mounts.as_ref()) {
        for m in mounts {
            let target = match m.target.as_deref() {
                Some(t) if !t.is_empty() => t,
                _ => continue,
            };
            let source = m.source.as_deref().unwrap_or("");
            let kind = m.typ.unwrap_or(MountTypeEnum::EMPTY);
            let ro = m.read_only.unwrap_or(false);
            let s = match kind {
                MountTypeEnum::BIND | MountTypeEnum::VOLUME => {
                    let mut s = format!("{source}:{target}");
                    if ro {
                        s.push_str(":ro");
                    }
                    s
                }
                MountTypeEnum::TMPFS => continue, // express via tmpfs:; v0.3d
                _ => continue,
            };
            if seen.insert(s.clone()) {
                out.push(s);
            }
        }
    }

    out.sort();
    out
}

/// Filter `Config.Env` to user-visible vars. Strips:
///
/// - `PATH` (set by image; almost never user-meaningful)
/// - `HOSTNAME` (Docker's auto-set short id)
/// - Anything starting with `com.docker.` or `COMPOSE_` (compose-injected)
///
/// Returns `(key, value)` pairs sorted alphabetically by key for stable
/// diffs. Keys without `=` (rare; clear-the-env-var syntax) are kept as
/// `key: ""`.
fn build_environment(env: &[String]) -> Vec<(String, String)> {
    let mut out: Vec<(String, String)> = Vec::new();
    for e in env {
        let (k, v) = match e.split_once('=') {
            Some((k, v)) => (k.to_string(), v.to_string()),
            None => (e.clone(), String::new()),
        };
        if k == "PATH" || k == "HOSTNAME" {
            continue;
        }
        if k.starts_with("com.docker.") || k.starts_with("COMPOSE_") {
            continue;
        }
        out.push((k, v));
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

/// Convert a bollard `HealthConfig` into a compose `healthcheck:` mapping.
/// Times come back from Docker in nanoseconds; compose wants `1m30s` style
/// strings. We emit seconds (`5s`) since that's what almost every
/// hand-written healthcheck uses.
fn build_healthcheck(hc: &bollard::secret::HealthConfig) -> Option<Mapping> {
    let mut m = Mapping::new();
    if let Some(test) = hc.test.as_ref() {
        if !test.is_empty() {
            m.insert(Value::String("test".into()), string_seq(test));
        }
    }
    if let Some(interval_ns) = hc.interval {
        if interval_ns > 0 {
            m.insert(
                Value::String("interval".into()),
                Value::String(format_duration_ns(interval_ns)),
            );
        }
    }
    if let Some(timeout_ns) = hc.timeout {
        if timeout_ns > 0 {
            m.insert(
                Value::String("timeout".into()),
                Value::String(format_duration_ns(timeout_ns)),
            );
        }
    }
    if let Some(retries) = hc.retries {
        if retries > 0 {
            m.insert(
                Value::String("retries".into()),
                Value::Number(serde_yaml::Number::from(retries)),
            );
        }
    }
    if let Some(start_ns) = hc.start_period {
        if start_ns > 0 {
            m.insert(
                Value::String("start_period".into()),
                Value::String(format_duration_ns(start_ns)),
            );
        }
    }
    if m.is_empty() { None } else { Some(m) }
}

/// Render a Docker-API nanosecond duration as a compose-friendly string.
/// Whole seconds when possible (`30s`), milliseconds otherwise (`500ms`).
fn format_duration_ns(ns: i64) -> String {
    if ns >= 1_000_000_000 && ns % 1_000_000_000 == 0 {
        format!("{}s", ns / 1_000_000_000)
    } else if ns >= 1_000_000 && ns % 1_000_000 == 0 {
        format!("{}ms", ns / 1_000_000)
    } else {
        // Fallback: round to ms so we don't emit weird precise values.
        format!("{}ms", (ns / 1_000_000).max(1))
    }
}

fn restart_policy_str(p: RestartPolicyNameEnum) -> Option<&'static str> {
    match p {
        RestartPolicyNameEnum::EMPTY => None,
        RestartPolicyNameEnum::NO => Some("no"),
        RestartPolicyNameEnum::ALWAYS => Some("always"),
        RestartPolicyNameEnum::UNLESS_STOPPED => Some("unless-stopped"),
        RestartPolicyNameEnum::ON_FAILURE => Some("on-failure"),
    }
}

/// Drop labels compose itself injects (`com.docker.compose.*`) and
/// Isengard's own managed-by markers. Returns sorted `(k, v)` pairs.
fn filter_labels(labels: &std::collections::HashMap<String, String>) -> Vec<(String, String)> {
    let mut out: Vec<(String, String)> = labels
        .iter()
        .filter(|(k, _)| !k.starts_with("com.docker.compose."))
        .map(|(k, v)| (k.clone(), v.clone()))
        .collect();
    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

fn string_seq(items: &[String]) -> Value {
    Value::Sequence(items.iter().cloned().map(Value::String).collect())
}

#[cfg(test)]
mod tests {
    use super::*;
    use bollard::secret::{
        ContainerConfig, EndpointSettings, HealthConfig, HostConfig, HostConfigLogConfig, Mount,
        NetworkSettings, PortBinding, RestartPolicy,
    };
    use std::collections::HashMap;

    fn empty_inspect() -> ContainerInspectResponse {
        ContainerInspectResponse {
            id: Some("c1".into()),
            name: Some("/hello-web".into()),
            ..Default::default()
        }
    }

    #[test]
    fn maps_image_into_compose_image_key() {
        let mut inspect = empty_inspect();
        inspect.config = Some(ContainerConfig {
            image: Some("nginxdemos/hello:plain-text".into()),
            ..Default::default()
        });
        let yaml = build_compose("hello", &[inspect], None).unwrap();
        assert!(yaml.contains("image: nginxdemos/hello:plain-text"));
    }

    #[test]
    fn maps_cmd_and_entrypoint() {
        let mut inspect = empty_inspect();
        inspect.config = Some(ContainerConfig {
            cmd: Some(vec!["nginx".into(), "-g".into(), "daemon off;".into()]),
            entrypoint: Some(vec!["/docker-entrypoint.sh".into()]),
            ..Default::default()
        });
        let yaml = build_compose("hello", &[inspect], None).unwrap();
        // entrypoint emitted before command (insertion order from build_service).
        assert!(yaml.contains("entrypoint:"));
        assert!(yaml.contains("/docker-entrypoint.sh"));
        assert!(yaml.contains("command:"));
        assert!(yaml.contains("daemon off;"));
    }

    #[test]
    fn maps_port_bindings_to_compose_ports() {
        let mut inspect = empty_inspect();
        let mut pb: HashMap<String, Option<Vec<PortBinding>>> = HashMap::new();
        pb.insert(
            "80/tcp".into(),
            Some(vec![PortBinding {
                host_ip: Some("0.0.0.0".into()),
                host_port: Some("8080".into()),
            }]),
        );
        pb.insert(
            "53/udp".into(),
            Some(vec![PortBinding {
                host_ip: Some("127.0.0.1".into()),
                host_port: Some("53".into()),
            }]),
        );
        inspect.host_config = Some(HostConfig {
            port_bindings: Some(pb),
            ..Default::default()
        });
        let yaml = build_compose("hello", &[inspect], None).unwrap();
        assert!(yaml.contains("0.0.0.0:8080:80"));
        assert!(yaml.contains("127.0.0.1:53:53/udp"));
    }

    #[test]
    fn merges_binds_and_mounts() {
        let mut inspect = empty_inspect();
        inspect.host_config = Some(HostConfig {
            binds: Some(vec!["/srv/data:/var/lib/data:ro".into()]),
            mounts: Some(vec![Mount {
                target: Some("/var/cache".into()),
                source: Some("cache-vol".into()),
                typ: Some(MountTypeEnum::VOLUME),
                read_only: Some(false),
                ..Default::default()
            }]),
            ..Default::default()
        });
        let yaml = build_compose("hello", &[inspect], None).unwrap();
        assert!(yaml.contains("/srv/data:/var/lib/data:ro"));
        assert!(yaml.contains("cache-vol:/var/cache"));
    }

    #[test]
    fn filters_compose_injected_env() {
        let mut inspect = empty_inspect();
        inspect.config = Some(ContainerConfig {
            env: Some(vec![
                "PATH=/usr/local/sbin".into(),
                "POSTGRES_PASSWORD=secret".into(),
                "COMPOSE_PROJECT_NAME=hello".into(),
                "HOSTNAME=abc123".into(),
                "TZ=UTC".into(),
            ]),
            ..Default::default()
        });
        let yaml = build_compose("hello", &[inspect], None).unwrap();
        assert!(yaml.contains("POSTGRES_PASSWORD: secret"));
        assert!(yaml.contains("TZ: UTC"));
        assert!(!yaml.contains("PATH:"));
        assert!(!yaml.contains("COMPOSE_PROJECT_NAME"));
        assert!(!yaml.contains("HOSTNAME:"));
    }

    #[test]
    fn maps_healthcheck_with_durations() {
        let mut inspect = empty_inspect();
        inspect.config = Some(ContainerConfig {
            healthcheck: Some(HealthConfig {
                test: Some(vec![
                    "CMD".into(),
                    "wget".into(),
                    "-qO-".into(),
                    "http://localhost/".into(),
                ]),
                interval: Some(5_000_000_000),
                timeout: Some(3_000_000_000),
                retries: Some(3),
                start_period: Some(5_000_000_000),
                ..Default::default()
            }),
            ..Default::default()
        });
        let yaml = build_compose("hello", &[inspect], None).unwrap();
        assert!(yaml.contains("interval: 5s"));
        assert!(yaml.contains("timeout: 3s"));
        assert!(yaml.contains("retries: 3"));
        assert!(yaml.contains("start_period: 5s"));
        assert!(yaml.contains("- CMD"));
    }

    #[test]
    fn maps_restart_policy() {
        let mut inspect = empty_inspect();
        inspect.host_config = Some(HostConfig {
            restart_policy: Some(RestartPolicy {
                name: Some(RestartPolicyNameEnum::UNLESS_STOPPED),
                maximum_retry_count: Some(0),
            }),
            ..Default::default()
        });
        let yaml = build_compose("hello", &[inspect], None).unwrap();
        assert!(yaml.contains("restart: unless-stopped"));
    }

    #[test]
    fn drops_compose_labels_and_keeps_user_labels() {
        let mut inspect = empty_inspect();
        let mut labels: HashMap<String, String> = HashMap::new();
        labels.insert("com.docker.compose.project".into(), "hello".into());
        labels.insert("com.docker.compose.service".into(), "web".into());
        labels.insert("isengard.enable".into(), "true".into());
        labels.insert("traefik.http.routers.web.rule".into(), "Host(`x`)".into());
        inspect.config = Some(ContainerConfig {
            labels: Some(labels),
            ..Default::default()
        });
        let yaml = build_compose("hello", &[inspect], None).unwrap();
        assert!(yaml.contains("isengard.enable"));
        assert!(yaml.contains("traefik.http.routers.web.rule"));
        assert!(!yaml.contains("com.docker.compose.project"));
        assert!(!yaml.contains("com.docker.compose.service"));
    }

    #[test]
    fn skips_bridge_host_none_networks() {
        let mut inspect = empty_inspect();
        let mut networks: HashMap<String, EndpointSettings> = HashMap::new();
        networks.insert("bridge".into(), EndpointSettings::default());
        networks.insert("host".into(), EndpointSettings::default());
        networks.insert("none".into(), EndpointSettings::default());
        networks.insert("hello_default".into(), EndpointSettings::default());
        inspect.network_settings = Some(NetworkSettings {
            networks: Some(networks),
            ..Default::default()
        });
        let yaml = build_compose("hello", &[inspect], None).unwrap();
        assert!(yaml.contains("hello_default"));
        // bridge/host/none must not surface as service or top-level network.
        for forbidden in ["- bridge", "- host\n", "- none"] {
            assert!(
                !yaml.contains(forbidden),
                "unexpected leak of driver-only network: yaml = {yaml}"
            );
        }
    }

    #[test]
    fn services_emitted_in_alphabetical_order() {
        let mut a = empty_inspect();
        a.name = Some("/zeta".into());
        a.config = Some(ContainerConfig {
            image: Some("img:zeta".into()),
            labels: Some({
                let mut m = HashMap::new();
                m.insert("com.docker.compose.service".into(), "zeta".into());
                m
            }),
            ..Default::default()
        });
        let mut b = empty_inspect();
        b.name = Some("/alpha".into());
        b.config = Some(ContainerConfig {
            image: Some("img:alpha".into()),
            labels: Some({
                let mut m = HashMap::new();
                m.insert("com.docker.compose.service".into(), "alpha".into());
                m
            }),
            ..Default::default()
        });
        let yaml = build_compose("hello", &[a, b], None).unwrap();
        let alpha_pos = yaml.find("alpha:").unwrap();
        let zeta_pos = yaml.find("zeta:").unwrap();
        assert!(
            alpha_pos < zeta_pos,
            "expected alphabetical service ordering, got {yaml}"
        );
    }

    #[test]
    fn x_isengard_host_emitted_when_provided() {
        let mut inspect = empty_inspect();
        inspect.config = Some(ContainerConfig {
            image: Some("nginx".into()),
            ..Default::default()
        });
        let yaml = build_compose("hello", &[inspect], Some("01ARZ3HOST")).unwrap();
        assert!(yaml.contains("x-isengard.host: 01ARZ3HOST"));
    }

    #[test]
    fn header_starts_yaml_output() {
        let mut inspect = empty_inspect();
        inspect.config = Some(ContainerConfig {
            image: Some("nginx".into()),
            ..Default::default()
        });
        let yaml = build_compose("hello", &[inspect], None).unwrap();
        assert!(yaml.starts_with(HEADER));
    }

    /// Round-trip: build twice, hashes match.
    #[test]
    fn round_trip_is_byte_identical() {
        let inspect = full_fixture();
        let slice = std::slice::from_ref(&inspect);
        let a = build_compose("hello", slice, None).unwrap();
        let b = build_compose("hello", slice, None).unwrap();
        assert_eq!(a, b);
    }

    /// Snapshot test: golden output for the hello-stack fixture.
    /// Update via `UPDATE_SNAPSHOT=1 cargo test compose_snapshot`.
    #[test]
    fn compose_snapshot_matches_golden() {
        let inspect = full_fixture();
        let yaml = build_compose("hello", &[inspect], None).unwrap();

        let golden_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests")
            .join("fixtures")
            .join("hello-stack.compose.golden.yaml");
        if std::env::var("UPDATE_SNAPSHOT").is_ok() {
            std::fs::write(&golden_path, &yaml).expect("write golden");
            return;
        }
        let golden = std::fs::read_to_string(&golden_path).unwrap_or_default();
        assert_eq!(
            yaml.trim_end(),
            golden.trim_end(),
            "snapshot drift; rerun with UPDATE_SNAPSHOT=1 to refresh"
        );
    }

    fn full_fixture() -> ContainerInspectResponse {
        let mut labels: HashMap<String, String> = HashMap::new();
        labels.insert("com.docker.compose.project".into(), "hello".into());
        labels.insert("com.docker.compose.service".into(), "hello".into());
        labels.insert("com.docker.compose.config-hash".into(), "abc".into());
        labels.insert("isengard.enable".into(), "true".into());
        labels.insert("isengard.expose.host".into(), "hello.local".into());

        let mut pb: HashMap<String, Option<Vec<PortBinding>>> = HashMap::new();
        pb.insert(
            "80/tcp".into(),
            Some(vec![PortBinding {
                host_ip: Some("0.0.0.0".into()),
                host_port: Some("8080".into()),
            }]),
        );

        let mut networks: HashMap<String, EndpointSettings> = HashMap::new();
        networks.insert("hello_default".into(), EndpointSettings::default());

        ContainerInspectResponse {
            id: Some("c1".into()),
            name: Some("/hello-web".into()),
            config: Some(ContainerConfig {
                image: Some("nginxdemos/hello:plain-text".into()),
                env: Some(vec!["PATH=/usr/sbin".into(), "TZ=UTC".into()]),
                labels: Some(labels),
                healthcheck: Some(HealthConfig {
                    test: Some(vec![
                        "CMD".into(),
                        "wget".into(),
                        "-qO-".into(),
                        "http://localhost/".into(),
                    ]),
                    interval: Some(5_000_000_000),
                    timeout: Some(3_000_000_000),
                    retries: Some(3),
                    start_period: Some(5_000_000_000),
                    ..Default::default()
                }),
                ..Default::default()
            }),
            host_config: Some(HostConfig {
                port_bindings: Some(pb),
                restart_policy: Some(RestartPolicy {
                    name: Some(RestartPolicyNameEnum::UNLESS_STOPPED),
                    maximum_retry_count: Some(0),
                }),
                log_config: Some(HostConfigLogConfig::default()),
                ..Default::default()
            }),
            network_settings: Some(NetworkSettings {
                networks: Some(networks),
                ..Default::default()
            }),
            ..Default::default()
        }
    }
}
