//! gRPC service definitions for Isengard v1.
//!
//! Generated by `tonic-build` from `proto/isengard.v1.proto`. The generated
//! module is re-exported as `pb` and used by `isengard-controller` (server)
//! and `isengard-agent` (client).

#![allow(clippy::all, missing_docs)]

pub mod pb {
    tonic::include_proto!("isengard.v1");
}

/// Encoded `FileDescriptorSet` for the v1 service. Used by `tonic-reflection`
/// to expose the schema over the wire (so `grpcurl` and similar tools work
/// without a local copy of the .proto file).
pub const FILE_DESCRIPTOR_SET: &[u8] =
    tonic::include_file_descriptor_set!("isengard_descriptor");
