//! gRPC wire types for Isengard v1.
//!
//! The crate carries the protobuf schema and the tonic-generated code
//! that backs every controller / agent RPC. Two consumers depend on
//! it:
//!
//! - [`isengard-controller`] embeds [`pb::controller_server`] to serve
//!   the v1 surface.
//! - [`isengard-agent`] embeds [`pb::controller_client`] to call it.
//!
//! Most items in this crate are generated by `tonic-build` from
//! [`proto/isengard.v1.proto`]. The hand-written surface is small:
//!
//! - The `pb` module declaration ([`pb`]).
//! - The descriptor-set constant ([`FILE_DESCRIPTOR_SET`]) used by
//!   gRPC reflection.
//! - The [`From<CoreEvent>`] / [`TryFrom<ProtoEvent>`] conversions
//!   that bridge the wire `Event` to [`isengard_core::Event`].
//!
//! The `.proto` source carries the canonical field-level docs;
//! `tonic-build` emits them as `///` doc comments on the generated
//! Rust types. Touch the comments there, not here.
//!
//! [`isengard-controller`]: ../isengard_controller/index.html
//! [`isengard-agent`]: ../isengard_agent/index.html
//! [`proto/isengard.v1.proto`]: ../../../../crates/isengard-proto/proto/isengard.v1.proto

#![warn(missing_docs)]
// `clippy::missing_docs_in_private_items` is intentionally NOT enabled
// for this crate: the `pb` module is generated by `tonic-build` and
// carries private items we can't doc.

/// Generated protobuf types and gRPC service stubs for `isengard.v1`.
///
/// Built by `tonic-build` from [`proto/isengard.v1.proto`]. The module
/// exposes one item per message, enum, oneof variant, plus
/// `controller_client::ControllerClient` (used by the agent) and
/// `controller_server::Controller` (implemented by the controller).
///
/// Field-level documentation rides on the generated types via comments
/// in the `.proto` source. Edit the `.proto` to change them; the
/// generated `///` comments regenerate on the next `cargo build`.
///
/// [`proto/isengard.v1.proto`]: ../../../../crates/isengard-proto/proto/isengard.v1.proto
#[allow(clippy::all, missing_docs, rustdoc::all)]
pub mod pb {
    tonic::include_proto!("isengard.v1");
}

/// Encoded `FileDescriptorSet` for the v1 service.
///
/// Wired into `tonic-reflection` on the controller so `grpcurl` and
/// similar tools can introspect the schema over the wire without a
/// local copy of the `.proto` file.
pub const FILE_DESCRIPTOR_SET: &[u8] = tonic::include_file_descriptor_set!("isengard_descriptor");

use crate::pb::Event as ProtoEvent;
use chrono::{DateTime, Utc};
use isengard_core::Event as CoreEvent;

#[doc = include_str!("../docs/event-conversion.md")]
impl From<CoreEvent> for ProtoEvent {
    fn from(e: CoreEvent) -> Self {
        ProtoEvent {
            kind: e.kind,
            occurred_at: e.occurred_at.to_rfc3339(),
            summary: e.summary,
            container_name: e.container_name,
            image: e.image,
            old_digest: e.old_digest,
            new_digest: e.new_digest,
            error: e.error,
            metadata_json: if e.metadata.is_null() {
                None
            } else {
                Some(e.metadata.to_string())
            },
        }
    }
}

impl TryFrom<ProtoEvent> for CoreEvent {
    type Error = String;

    /// Parses a wire [`ProtoEvent`] back to its core twin.
    ///
    /// See the [`From<CoreEvent>`] impl for the field-by-field mapping.
    /// `host_id` is left unset: the controller stamps it from the
    /// connection's mTLS identity on receipt.
    ///
    /// # Errors
    ///
    /// Returns `Err(String)` when `occurred_at` is not a valid RFC3339
    /// timestamp, or when `metadata_json` is set but does not parse as
    /// JSON.
    fn try_from(p: ProtoEvent) -> Result<Self, String> {
        let occurred_at = DateTime::parse_from_rfc3339(&p.occurred_at)
            .map_err(|e| format!("bad occurred_at: {e}"))?
            .with_timezone(&Utc);
        let metadata = match p.metadata_json {
            Some(s) if !s.is_empty() => {
                serde_json::from_str(&s).map_err(|e| format!("bad metadata_json: {e}"))?
            }
            _ => serde_json::Value::Null,
        };
        Ok(CoreEvent {
            kind: p.kind,
            occurred_at,
            // Set by the controller from the connection context.
            host_id: None,
            summary: p.summary,
            container_name: p.container_name,
            image: p.image,
            old_digest: p.old_digest,
            new_digest: p.new_digest,
            error: p.error,
            metadata,
        })
    }
}
