[package]
name = "isengard-plugin-dashboard"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Dashboard plugin for Isengard: Nuxt 3 SPA + axum"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
chrono.workspace = true
inventory.workspace = true
isengard-controller.workspace = true
isengard-core.workspace = true
isengard-storage.workspace = true
mime_guess.workspace = true
reqwest.workspace = true
rust-embed.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true }
tower.workspace = true
tracing.workspace = true
ulid.workspace = true
