[package]
name = "isengard-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Agent-mode runtime"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bollard.workspace = true
hostname.workspace = true
isengard-core.workspace = true
isengard-proto.workspace = true
pingora-core = { workspace = true }
pingora-proxy = { workspace = true }
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true }
tokio-stream.workspace = true
tonic.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile = "3.14.0"
chrono.workspace = true
isengard-controller = { workspace = true }
isengard-storage = { workspace = true }
