name: Pages

on:
  workflow_dispatch:
  push:
    branches: [main, next]
    paths:
      - .github/workflows/pages.yml
      - README.md
      - bun.lock
      - bun.lockb
      - docs/**
      - package*.json
      - website/**
  pull_request:
    paths:
      - .github/workflows/pages.yml
      - README.md
      - bun.lock
      - bun.lockb
      - docs/**
      - package*.json
      - website/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
        working-directory: website

      - name: Build
        run: bun run generate
        working-directory: website

      - name: Deploy to Cloudflare Pages
        if: github.event_name != 'pull_request'
        run: bunx wrangler pages deploy website/.output/public --project-name=isengard
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
